name: Build & Push MinIO Operator

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag da imagem (ex: v6.0.4)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GCR_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build image
        run: |
          IMAGE="${{ secrets.GCR_REGISTRY }}/minio/operator:${{ github.event.inputs.version }}"
          echo "Building $IMAGE"
          docker build -t $IMAGE .

      - name: Push image
        run: |
          IMAGE="${{ secrets.GCR_REGISTRY }}/minio/operator:${{ github.event.inputs.version }}"
          echo "Pushing $IMAGE"
          docker push $IMAGE

      - name: Done
        run: echo "Operator built and pushed successfully!"
